#age:
#   docker-compose up --force-recreate
# docker pull elgalu/selenium'
version: '2.1'

services:
  #--------------#
  selenium:
   image: elgalu/selenium
  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 12
            --maxDockerSeleniumContainers 20
            --screenWidth 1920 --screenHeight 1080
            --timeZone "Europe/London"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --maxTestSessions 1
            --sendAnonymousUsageInfo false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY
      - LT_USERNAME
      - LT_ACCESS_KEY
      - SEL_RELEASE_TIMEOUT_SECS=720
      - ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache
      #- PULL_SELENIUM_IMAGE=true
      #- ZALENIUM_PROXY_CLEANUP_TIMEOUT=1800

  mock:
    image: elgalu/google_adwords_mock
    depends_on:
      - zalenium
    ports:
      - 8080:8080
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080










